apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace }}
data:
  haproxy.cfg: |
    global
      nbthread 1
      maxconn 128
    defaults
      mode tcp
      timeout connect 5s
      timeout client 60s
      timeout server 60s
    frontend s3
      bind :8333
      default_backend local_s3
    backend local_s3
      server local 127.0.0.1:9000 check
